# Generated by Django 4.1.4 on 2022-12-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CessaoFundo',
            fields=[
                ('ID_CESSAO', models.IntegerField(primary_key=True, serialize=False)),
                ('ORIGINADOR', models.CharField(max_length=250)),
                ('DOC_ORIGINADOR', models.IntegerField()),
                ('CEDENTE', models.CharField(max_length=250)),
                ('CCB', models.IntegerField()),
                ('ID_EXTERNO', models.IntegerField()),
                ('CLIENTE', models.CharField(max_length=250)),
                ('CPF_CNPJ', models.CharField(max_length=50)),
                ('ENDEREÇO', models.CharField(max_length=250)),
                ('CEP', models.CharField(max_length=50)),
                ('CIDADE', models.CharField(max_length=250)),
                ('UF', models.CharField(max_length=50)),
                ('VALOR_DO_EMPRESTIMO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VALOR_DA_PARCELA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TOTAL_PARCELAS', models.IntegerField()),
                ('PARCELA', models.IntegerField()),
                ('DATA_DE_EMISSAO', models.DateField()),
                ('DATA_DE_VENCIMENTO', models.DateField()),
                ('PRECO_DE_AQUISICAO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
