# Generated by Django 4.1.4 on 2022-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeempirica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cessaofundo',
            name='ID_CESSAO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
