# Generated by Django 4.1.4 on 2022-12-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeempirica', '0002_alter_cessaofundo_id_cessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cessaofundo',
            name='DOC_CEDENTE',
            field=models.IntegerField(default=0),
        ),
    ]
